# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: 'doctrine://default'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            mail_sender:
                dsn: 'doctrine://default'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                    queue_name: send_mail_queue
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: []
        routing:
            App\Manager\Module\Notification\Message\WelcomeUser: mail_sender
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
